---
modules:
  - name: "application"
priority: ["application"]
shim:
  "ember":
    deps: ["jquery"]
    exports: "Ember"
  "ember-data":
    deps: ["ember"]
    exports: "DS"
  "jquery_ujs":
    deps: ["jquery"]
    exports: "jQuery"
  "templates/all":
    deps: ["ember"]
    exports: "Ember.Handlebars"
  "twitter/bootstrap":
    deps: ["jquery"]
    exports: "jQuery.fn.popover"
enforceDefine: true
